/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should be auto-generated by Next.js, but we're creating it manually
// to ensure TypeScript resolve works properly
